\set ON_ERROR_STOP on

SELECT 'CREATE DATABASE metabase OWNER xs'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'metabase')\gexec

ALTER DATABASE app_db OWNER TO xs;
GRANT ALL PRIVILEGES ON DATABASE app_db TO xs;
GRANT ALL PRIVILEGES ON DATABASE metabase TO xs;
