CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'xsailxma';
ALTER USER 'repl'@'%' IDENTIFIED BY 'xsailxma';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';
CREATE USER IF NOT EXISTS 'xs'@'%' IDENTIFIED BY 'xsailxma';
ALTER USER 'xs'@'%' IDENTIFIED BY 'xsailxma';
CREATE DATABASE IF NOT EXISTS app_db DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON app_db.* TO 'xs'@'%';
FLUSH PRIVILEGES;
