bind 0.0.0.0
port 6379
protected-mode yes

requirepass xsailxma
user default on >xsailxma ~* +@all
user xs on >xsailxma ~* +@all

dir /data
appendonly yes
appendfilename "appendonly.aof"
save 900 1
save 300 10
save 60 10000

logfile ""
loglevel notice

maxmemory-policy noeviction
