CREATE DATABASE IF NOT EXISTS app_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'xs'@'%' IDENTIFIED BY 'xsailxma';
ALTER USER 'xs'@'%' IDENTIFIED BY 'xsailxma';

GRANT ALL PRIVILEGES ON app_db.* TO 'xs'@'%';
GRANT SELECT, SHOW VIEW, PROCESS, REPLICATION CLIENT ON *.* TO 'xs'@'%';

FLUSH PRIVILEGES;
