listen_addresses = '*'
port = 5432
max_connections = 200
shared_buffers = 256MB
timezone = 'Asia/Shanghai'
log_timezone = 'Asia/Shanghai'
logging_collector = off
log_statement = 'none'
log_min_duration_statement = 1000
